import type { Metadata } from "next";
import styles from "./style.module.css";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={styles.authCard}>{children}</div>;
}
